services:
  nats-server:
    image: nats:latest
    ports:
      - ${NATS_PORT}:${NATS_PORT}

  client-gateway:
    build: ./client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - DATABASE_URL=${PRODUCTS_DB_URL}
      - NATS_SERVERS=${NATS_SERVERS}

  auth-ms:
    build: ./auth-ms
    ports:
      - ${AUTH_MS_PORT}:${AUTH_MS_PORT}
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${AUTH_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${AUTH_DB_URL}
      - JWT_SECRET=${JWT_SECRET}

  products-ms:
    build: ./products-ms
    ports:
      - ${PRODUCTS_MS_PORT}:${PRODUCTS_MS_PORT}
    volumes:
      - ./products-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${PRODUCTS_MS_PORT}
      - DATABASE_URL=${PRODUCTS_DB_URL}
      - NATS_SERVERS=${NATS_SERVERS}

  orders-ms:
    build: ./orders-ms
    ports:
      - ${ORDERS_MS_PORT}:${ORDERS_MS_PORT}
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${ORDERS_MS_PORT}
      - DATABASE_URL=${ORDER_DATABASE_URL}
      - NATS_SERVERS=${NATS_SERVERS}
    depends_on:
      - orders-db

  orders-db:
    container_name: orders_database
    image: postgres:16.2
    restart: always
    volumes:
      - ./orders-ms/postgres:/var/lib/postgresql/data
    ports:
      - ${ORDERS_DB_PORT}:${ORDERS_DB_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  payments-ms:
    container_name: payments_ms
    build: ./payments-ms
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    volumes:
      - ./payments-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
    