apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orders-ms
  name: orders-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-ms
  strategy: {}
  template:
    metadata:
      labels:
        app: orders-ms
    spec:
      containers:
      - image: orders-ms-prod
        name: orders-ms-prod
        imagePullPolicy: Never   # <--- usa las imÃ¡genes locales y no las de docker hub o de la web
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: "3002"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: orders-secrets
              key: database_url
        - name: NATS_SERVERS
          value: "nats://nats"
        resources: {}
status: {}
