apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: products-ms
  name: products-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-ms
  strategy: {}
  template:
    metadata:
      labels:
        app: products-ms
    spec:
      containers:
      - image: products-ms-prod
        name: products-ms-prod
        imagePullPolicy: Never   # <--- usa las imÃ¡genes locales y no las de docker hub o de la web
        env:
        - name: PORT
          value: "3001"
        - name: DATABASE_URL
          value: "file:/usr/src/app/dev.db"
        - name: NATS_SERVERS
          value: "nats://nats"
        resources: {}
status: {}
